// generated by conjunction (game_functions.py): the game's quest functions with enum parameters, callable
// from a quest block with the enum value as a name (radish cannot write enums)

quest function CjG_AT_AddAndEquipReSkill(skill : name, lvl : int) {
    var e_skill : ESkill;
    switch (skill) {
        case 'S_SUndefined': e_skill = S_SUndefined; break;
        case 'S_Sword_1': e_skill = S_Sword_1; break;
        case 'S_Sword_2': e_skill = S_Sword_2; break;
        case 'S_Sword_3': e_skill = S_Sword_3; break;
        case 'S_Sword_4': e_skill = S_Sword_4; break;
        case 'S_Sword_5': e_skill = S_Sword_5; break;
        case 'S_Magic_1': e_skill = S_Magic_1; break;
        case 'S_Magic_2': e_skill = S_Magic_2; break;
        case 'S_Magic_3': e_skill = S_Magic_3; break;
        case 'S_Magic_4': e_skill = S_Magic_4; break;
        case 'S_Magic_5': e_skill = S_Magic_5; break;
        case 'S_Alchemy_1': e_skill = S_Alchemy_1; break;
        case 'S_Alchemy_2': e_skill = S_Alchemy_2; break;
        case 'S_Alchemy_3': e_skill = S_Alchemy_3; break;
        case 'S_Alchemy_4': e_skill = S_Alchemy_4; break;
        case 'S_Alchemy_5': e_skill = S_Alchemy_5; break;
        case 'S_Sword_s01': e_skill = S_Sword_s01; break;
        case 'S_Sword_s02': e_skill = S_Sword_s02; break;
        case 'S_Sword_s03': e_skill = S_Sword_s03; break;
        case 'S_Sword_s04': e_skill = S_Sword_s04; break;
        case 'S_Sword_s05': e_skill = S_Sword_s05; break;
        case 'S_Sword_s06': e_skill = S_Sword_s06; break;
        case 'S_Sword_s07': e_skill = S_Sword_s07; break;
        case 'S_Sword_s08': e_skill = S_Sword_s08; break;
        case 'S_Sword_s09': e_skill = S_Sword_s09; break;
        case 'S_Sword_s10': e_skill = S_Sword_s10; break;
        case 'S_Sword_s11': e_skill = S_Sword_s11; break;
        case 'S_Sword_s12': e_skill = S_Sword_s12; break;
        case 'S_Sword_s13': e_skill = S_Sword_s13; break;
        case 'S_UNUSED1': e_skill = S_UNUSED1; break;
        case 'S_Sword_s15': e_skill = S_Sword_s15; break;
        case 'S_Sword_s16': e_skill = S_Sword_s16; break;
        case 'S_Sword_s17': e_skill = S_Sword_s17; break;
        case 'S_Sword_s18': e_skill = S_Sword_s18; break;
        case 'S_Sword_s19': e_skill = S_Sword_s19; break;
        case 'S_Sword_s20': e_skill = S_Sword_s20; break;
        case 'S_Sword_s21': e_skill = S_Sword_s21; break;
        case 'S_Sword_s22': e_skill = S_Sword_s22; break;
        case 'S_Sword_s23': e_skill = S_Sword_s23; break;
        case 'S_Sword_s24': e_skill = S_Sword_s24; break;
        case 'S_Sword_s25': e_skill = S_Sword_s25; break;
        case 'S_Sword_s26': e_skill = S_Sword_s26; break;
        case 'S_Sword_s27': e_skill = S_Sword_s27; break;
        case 'S_Sword_s28': e_skill = S_Sword_s28; break;
        case 'S_Sword_s29': e_skill = S_Sword_s29; break;
        case 'S_Sword_s30': e_skill = S_Sword_s30; break;
        case 'S_Sword_s31': e_skill = S_Sword_s31; break;
        case 'S_Sword_s32': e_skill = S_Sword_s32; break;
        case 'S_Sword_s33': e_skill = S_Sword_s33; break;
        case 'S_Sword_s34': e_skill = S_Sword_s34; break;
        case 'S_Sword_s35': e_skill = S_Sword_s35; break;
        case 'S_Sword_s36': e_skill = S_Sword_s36; break;
        case 'S_Magic_s01': e_skill = S_Magic_s01; break;
        case 'S_Magic_s02': e_skill = S_Magic_s02; break;
        case 'S_Magic_s03': e_skill = S_Magic_s03; break;
        case 'S_Magic_s04': e_skill = S_Magic_s04; break;
        case 'S_Magic_s05': e_skill = S_Magic_s05; break;
        case 'S_Magic_s06': e_skill = S_Magic_s06; break;
        case 'S_Magic_s07': e_skill = S_Magic_s07; break;
        case 'S_Magic_s08': e_skill = S_Magic_s08; break;
        case 'S_Magic_s09': e_skill = S_Magic_s09; break;
        case 'S_Magic_s10': e_skill = S_Magic_s10; break;
        case 'S_Magic_s11': e_skill = S_Magic_s11; break;
        case 'S_Magic_s12': e_skill = S_Magic_s12; break;
        case 'S_Magic_s13': e_skill = S_Magic_s13; break;
        case 'S_Magic_s14': e_skill = S_Magic_s14; break;
        case 'S_Magic_s15': e_skill = S_Magic_s15; break;
        case 'S_Magic_s16': e_skill = S_Magic_s16; break;
        case 'S_Magic_s17': e_skill = S_Magic_s17; break;
        case 'S_Magic_s18': e_skill = S_Magic_s18; break;
        case 'S_Magic_s19': e_skill = S_Magic_s19; break;
        case 'S_Magic_s20': e_skill = S_Magic_s20; break;
        case 'S_Magic_s21': e_skill = S_Magic_s21; break;
        case 'S_Magic_s22': e_skill = S_Magic_s22; break;
        case 'S_Magic_s23': e_skill = S_Magic_s23; break;
        case 'S_Magic_s24': e_skill = S_Magic_s24; break;
        case 'S_Magic_s25': e_skill = S_Magic_s25; break;
        case 'S_Magic_s26': e_skill = S_Magic_s26; break;
        case 'S_Magic_s27': e_skill = S_Magic_s27; break;
        case 'S_Magic_s28': e_skill = S_Magic_s28; break;
        case 'S_Magic_s29': e_skill = S_Magic_s29; break;
        case 'S_Magic_s30': e_skill = S_Magic_s30; break;
        case 'S_Magic_s31': e_skill = S_Magic_s31; break;
        case 'S_Magic_s32': e_skill = S_Magic_s32; break;
        case 'S_Magic_s33': e_skill = S_Magic_s33; break;
        case 'S_Magic_s34': e_skill = S_Magic_s34; break;
        case 'S_Magic_s35': e_skill = S_Magic_s35; break;
        case 'S_Magic_s36': e_skill = S_Magic_s36; break;
        case 'S_Magic_s37': e_skill = S_Magic_s37; break;
        case 'S_Magic_s38': e_skill = S_Magic_s38; break;
        case 'S_Magic_s39': e_skill = S_Magic_s39; break;
        case 'S_Magic_s40': e_skill = S_Magic_s40; break;
        case 'S_Magic_s41': e_skill = S_Magic_s41; break;
        case 'S_Magic_s42': e_skill = S_Magic_s42; break;
        case 'S_Alchemy_s22': e_skill = S_Alchemy_s22; break;
        case 'S_Alchemy_s23': e_skill = S_Alchemy_s23; break;
        case 'S_Alchemy_s24': e_skill = S_Alchemy_s24; break;
        case 'S_Alchemy_s25': e_skill = S_Alchemy_s25; break;
        case 'S_Alchemy_s26': e_skill = S_Alchemy_s26; break;
        case 'S_Alchemy_s27': e_skill = S_Alchemy_s27; break;
        case 'S_UNUSED2': e_skill = S_UNUSED2; break;
        case 'S_Alchemy_s01': e_skill = S_Alchemy_s01; break;
        case 'S_Alchemy_s02': e_skill = S_Alchemy_s02; break;
        case 'S_Alchemy_s03': e_skill = S_Alchemy_s03; break;
        case 'S_Alchemy_s04': e_skill = S_Alchemy_s04; break;
        case 'S_Alchemy_s05': e_skill = S_Alchemy_s05; break;
        case 'S_Alchemy_s06': e_skill = S_Alchemy_s06; break;
        case 'S_Alchemy_s07': e_skill = S_Alchemy_s07; break;
        case 'S_Alchemy_s08': e_skill = S_Alchemy_s08; break;
        case 'S_Alchemy_s09': e_skill = S_Alchemy_s09; break;
        case 'S_Alchemy_s10': e_skill = S_Alchemy_s10; break;
        case 'S_Alchemy_s11': e_skill = S_Alchemy_s11; break;
        case 'S_Alchemy_s12': e_skill = S_Alchemy_s12; break;
        case 'S_Alchemy_s13': e_skill = S_Alchemy_s13; break;
        case 'S_Alchemy_s14': e_skill = S_Alchemy_s14; break;
        case 'S_Alchemy_s15': e_skill = S_Alchemy_s15; break;
        case 'S_Alchemy_s16': e_skill = S_Alchemy_s16; break;
        case 'S_Alchemy_s17': e_skill = S_Alchemy_s17; break;
        case 'S_Alchemy_s18': e_skill = S_Alchemy_s18; break;
        case 'S_Alchemy_s19': e_skill = S_Alchemy_s19; break;
        case 'S_Alchemy_s20': e_skill = S_Alchemy_s20; break;
        case 'S_Skill_MAX': e_skill = S_Skill_MAX; break;
        case 'S_Perk_MIN': e_skill = S_Perk_MIN; break;
        case 'S_Perk_01': e_skill = S_Perk_01; break;
        case 'S_Perk_02': e_skill = S_Perk_02; break;
        case 'S_Perk_03': e_skill = S_Perk_03; break;
        case 'S_Perk_04': e_skill = S_Perk_04; break;
        case 'S_Perk_05': e_skill = S_Perk_05; break;
        case 'S_Perk_06': e_skill = S_Perk_06; break;
        case 'S_Perk_07': e_skill = S_Perk_07; break;
        case 'S_Perk_08': e_skill = S_Perk_08; break;
        case 'S_Perk_09': e_skill = S_Perk_09; break;
        case 'S_Perk_10': e_skill = S_Perk_10; break;
        case 'S_Perk_11': e_skill = S_Perk_11; break;
        case 'S_Perk_12': e_skill = S_Perk_12; break;
        case 'S_Perk_13': e_skill = S_Perk_13; break;
        case 'S_Perk_14': e_skill = S_Perk_14; break;
        case 'S_Perk_15': e_skill = S_Perk_15; break;
        case 'S_Perk_16': e_skill = S_Perk_16; break;
        case 'S_Perk_17': e_skill = S_Perk_17; break;
        case 'S_Perk_18': e_skill = S_Perk_18; break;
        case 'S_Perk_19': e_skill = S_Perk_19; break;
        case 'S_Perk_20': e_skill = S_Perk_20; break;
        case 'S_Perk_21': e_skill = S_Perk_21; break;
        case 'S_Perk_22': e_skill = S_Perk_22; break;
        case 'S_Perk_23': e_skill = S_Perk_23; break;
        case 'S_Perk_24': e_skill = S_Perk_24; break;
        case 'S_Perk_25': e_skill = S_Perk_25; break;
        case 'S_Perk_26': e_skill = S_Perk_26; break;
        case 'S_Perk_27': e_skill = S_Perk_27; break;
        case 'S_Perk_28': e_skill = S_Perk_28; break;
        case 'S_Perk_29': e_skill = S_Perk_29; break;
        case 'S_Perk_30': e_skill = S_Perk_30; break;
        case 'S_Perk_31': e_skill = S_Perk_31; break;
        case 'S_Perk_32': e_skill = S_Perk_32; break;
        case 'S_Perk_33': e_skill = S_Perk_33; break;
        case 'S_Perk_34': e_skill = S_Perk_34; break;
        case 'S_Perk_35': e_skill = S_Perk_35; break;
        case 'S_Perk_36': e_skill = S_Perk_36; break;
        case 'S_Perk_37': e_skill = S_Perk_37; break;
        case 'S_Perk_38': e_skill = S_Perk_38; break;
        case 'S_Perk_39': e_skill = S_Perk_39; break;
        case 'S_Perk_40': e_skill = S_Perk_40; break;
        case 'S_Perk_41': e_skill = S_Perk_41; break;
        case 'S_Perk_42': e_skill = S_Perk_42; break;
        case 'S_Perk_43': e_skill = S_Perk_43; break;
        case 'S_Perk_44': e_skill = S_Perk_44; break;
        case 'S_Perk_MAX': e_skill = S_Perk_MAX; break;
    }
    AT_AddAndEquipReSkill(e_skill, lvl);
}

quest function CjG_AddAllGwentCards(optional faction : name, optional ignoreLy : bool) {
    var e_faction : EGwentCardFaction;
    switch (faction) {
        case 'EGCF_Neutral': e_faction = EGCF_Neutral; break;
        case 'EGCF_Kingdoms': e_faction = EGCF_Kingdoms; break;
        case 'EGCF_Nilfgaard': e_faction = EGCF_Nilfgaard; break;
        case 'EGCF_Monsters': e_faction = EGCF_Monsters; break;
        case 'EGCF_Scoiatael': e_faction = EGCF_Scoiatael; break;
        case 'EGCG_Skellige': e_faction = EGCG_Skellige; break;
    }
    AddAllGwentCards(e_faction, ignoreLy);
}

quest function CjG_AddQuestMappinToNoticeboard(noticeboardTag : name, entityTag : name, entityType : name) {
    var e_entityType : AQMTN_EntityType;
    switch (entityType) {
        case 'AQMTN_Actor': e_entityType = AQMTN_Actor; break;
        case 'AQMTN_NonActor': e_entityType = AQMTN_NonActor; break;
    }
    AddQuestMappinToNoticeboard(noticeboardTag, entityTag, e_entityType);
}

quest function CjG_AnimalNervousState(npcsTag : name, reactionType : name, percents : int) {
    var e_reactionType : EAnimalReaction;
    switch (reactionType) {
        case 'AR_Rearing': e_reactionType = AR_Rearing; break;
        case 'AR_Kick': e_reactionType = AR_Kick; break;
        case 'AR_Backing': e_reactionType = AR_Backing; break;
        case 'AR_AddPanicPercents': e_reactionType = AR_AddPanicPercents; break;
    }
    AnimalNervousState(npcsTag, e_reactionType, percents);
}

quest function CjG_AssignNPCTemporaryGroupAttitudeQuest(npcTag : name, attGroup : name, priority : name, value : bool) {
    var e_priority : EAttitudeGroupPriority;
    switch (priority) {
        case 'AGP_Default': e_priority = AGP_Default; break;
        case 'AGP_SpawnTree': e_priority = AGP_SpawnTree; break;
        case 'AGP_Axii': e_priority = AGP_Axii; break;
        case 'AGP_Fistfight': e_priority = AGP_Fistfight; break;
        case 'AGP_Scenes': e_priority = AGP_Scenes; break;
    }
    AssignNPCTemporaryGroupAttitudeQuest(npcTag, attGroup, e_priority, value);
}

quest function CjG_ChangeCombatStyleByTag(preferedCombatStyle : name, npcTag : name) {
    var e_preferedCombatStyle : EBehaviorGraph;
    switch (preferedCombatStyle) {
        case 'EBG_None': e_preferedCombatStyle = EBG_None; break;
        case 'EBG_Combat_Undefined': e_preferedCombatStyle = EBG_Combat_Undefined; break;
        case 'EBG_Combat_Shield': e_preferedCombatStyle = EBG_Combat_Shield; break;
        case 'EBG_Combat_1Handed_Sword': e_preferedCombatStyle = EBG_Combat_1Handed_Sword; break;
        case 'EBG_Combat_1Handed_Axe': e_preferedCombatStyle = EBG_Combat_1Handed_Axe; break;
        case 'EBG_Combat_1Handed_Blunt': e_preferedCombatStyle = EBG_Combat_1Handed_Blunt; break;
        case 'EBG_Combat_1Handed_Any': e_preferedCombatStyle = EBG_Combat_1Handed_Any; break;
        case 'EBG_Combat_2Handed_Any': e_preferedCombatStyle = EBG_Combat_2Handed_Any; break;
        case 'EBG_Combat_2Handed_Sword': e_preferedCombatStyle = EBG_Combat_2Handed_Sword; break;
        case 'EBG_Combat_2Handed_Hammer': e_preferedCombatStyle = EBG_Combat_2Handed_Hammer; break;
        case 'EBG_Combat_2Handed_Axe': e_preferedCombatStyle = EBG_Combat_2Handed_Axe; break;
        case 'EBG_Combat_2Handed_Halberd': e_preferedCombatStyle = EBG_Combat_2Handed_Halberd; break;
        case 'EBG_Combat_2Handed_Spear': e_preferedCombatStyle = EBG_Combat_2Handed_Spear; break;
        case 'EBG_Combat_2Handed_Staff': e_preferedCombatStyle = EBG_Combat_2Handed_Staff; break;
        case 'EBG_Combat_Fists': e_preferedCombatStyle = EBG_Combat_Fists; break;
        case 'EBG_Combat_Bow': e_preferedCombatStyle = EBG_Combat_Bow; break;
        case 'EBG_Combat_Crossbow': e_preferedCombatStyle = EBG_Combat_Crossbow; break;
        case 'EBG_Combat_Witcher': e_preferedCombatStyle = EBG_Combat_Witcher; break;
        case 'EBG_Combat_Sorceress': e_preferedCombatStyle = EBG_Combat_Sorceress; break;
        case 'EBG_Combat_WildHunt_Imlerith': e_preferedCombatStyle = EBG_Combat_WildHunt_Imlerith; break;
        case 'EBG_Combat_WildHunt_Imlerith_Second_Stage': e_preferedCombatStyle = EBG_Combat_WildHunt_Imlerith_Second_Stage; break;
        case 'EBG_Combat_WildHunt_Caranthir': e_preferedCombatStyle = EBG_Combat_WildHunt_Caranthir; break;
        case 'EBG_Combat_WildHunt_Caranthir_Second_Stage': e_preferedCombatStyle = EBG_Combat_WildHunt_Caranthir_Second_Stage; break;
        case 'EBG_Combat_WildHunt_Eredin': e_preferedCombatStyle = EBG_Combat_WildHunt_Eredin; break;
        case 'EBG_Combat_Olgierd': e_preferedCombatStyle = EBG_Combat_Olgierd; break;
        case 'EBG_Combat_Caretaker': e_preferedCombatStyle = EBG_Combat_Caretaker; break;
        case 'EBG_Combat_Dettlaff_Vampire': e_preferedCombatStyle = EBG_Combat_Dettlaff_Vampire; break;
        case 'EBG_Combat_Gregoire': e_preferedCombatStyle = EBG_Combat_Gregoire; break;
        case 'EBG_Combat_Dettlaff_Minion': e_preferedCombatStyle = EBG_Combat_Dettlaff_Minion; break;
    }
    ChangeCombatStyleByTag(e_preferedCombatStyle, npcTag);
}

quest function CjG_ChangeNPCStateQuest(npcTag : name, npcState : name, ignoreImmortalityMode : bool) {
    var e_npcState : EQuestNPCStates;
    switch (npcState) {
        case 'EQNS_Default': e_npcState = EQNS_Default; break;
        case 'EQNS_Dead': e_npcState = EQNS_Dead; break;
        case 'EQNS_Agony': e_npcState = EQNS_Agony; break;
        case 'EQNS_KnockedUnconscious': e_npcState = EQNS_KnockedUnconscious; break;
        case 'EQNS_DeadNoAgony': e_npcState = EQNS_DeadNoAgony; break;
        case 'EQNS_DeadInstantRagdoll': e_npcState = EQNS_DeadInstantRagdoll; break;
        case 'EQNS_Combat': e_npcState = EQNS_Combat; break;
    }
    ChangeNPCStateQuest(npcTag, e_npcState, ignoreImmortalityMode);
}

quest function CjG_CombatStageChange(npcsTag : name, stage : name) {
    var e_stage : ENPCFightStage;
    switch (stage) {
        case 'NFS_Stage1': e_stage = NFS_Stage1; break;
        case 'NFS_Stage2': e_stage = NFS_Stage2; break;
        case 'NFS_Stage3': e_stage = NFS_Stage3; break;
        case 'NFS_Stage4': e_stage = NFS_Stage4; break;
        case 'NFS_Stage5': e_stage = NFS_Stage5; break;
    }
    CombatStageChange(npcsTag, e_stage);
}

quest function CjG_DoorChangeState(tag : name, newState : name, optional keyItemName : name, optional removeKeyOnUse : bool, optional smoooth : bool, optional dontBlockInCombat : bool) {
    var e_newState : EDoorQuestState;
    switch (newState) {
        case 'EDQS_Open': e_newState = EDQS_Open; break;
        case 'EDQS_Close': e_newState = EDQS_Close; break;
        case 'EDQS_RemoveLock': e_newState = EDQS_RemoveLock; break;
        case 'EDQS_Enable': e_newState = EDQS_Enable; break;
        case 'EDQS_Disable': e_newState = EDQS_Disable; break;
        case 'EDQS_Lock': e_newState = EDQS_Lock; break;
    }
    DoorChangeState(tag, e_newState, keyItemName, removeKeyOnUse, smoooth, dontBlockInCombat);
}

quest function CjG_DrawWeaponQuest(weapon : name, dontIgnoreDrawActionLock : bool) {
    var e_weapon : EDrawWeaponQuestType;
    switch (weapon) {
        case 'EDWQT_Steel': e_weapon = EDWQT_Steel; break;
        case 'EDWQT_Silver': e_weapon = EDWQT_Silver; break;
        case 'EDWQT_NoWeapon': e_weapon = EDWQT_NoWeapon; break;
        case 'EDWQT_Fists': e_weapon = EDWQT_Fists; break;
    }
    DrawWeaponQuest(e_weapon, dontIgnoreDrawActionLock);
}

quest function CjG_DrawWeaponWithCombatQuest(weapon : name, dontIgnoreDrawActionLock : bool) {
    var e_weapon : EDrawWeaponQuestType;
    switch (weapon) {
        case 'EDWQT_Steel': e_weapon = EDWQT_Steel; break;
        case 'EDWQT_Silver': e_weapon = EDWQT_Silver; break;
        case 'EDWQT_NoWeapon': e_weapon = EDWQT_NoWeapon; break;
        case 'EDWQT_Fists': e_weapon = EDWQT_Fists; break;
    }
    DrawWeaponWithCombatQuest(e_weapon, dontIgnoreDrawActionLock);
}

quest function CjG_EnableDynamicMappin(tag : name, optional enable : bool, optional type : name, optional showAlways : bool) {
    var e_type : EDM_MappinType;
    switch (type) {
        case 'EDM_QuestAvailable': e_type = EDM_QuestAvailable; break;
        case 'EDM_MonsterNest': e_type = EDM_MonsterNest; break;
        case 'EDM_Prostitute': e_type = EDM_Prostitute; break;
        case 'EDM_HorseRacingNPC': e_type = EDM_HorseRacingNPC; break;
        case 'EDM_NonQuestHorseRace': e_type = EDM_NonQuestHorseRace; break;
        case 'EDM_QuestAvailableFromNonActor': e_type = EDM_QuestAvailableFromNonActor; break;
        case 'EDM_EP1QuestAvailable': e_type = EDM_EP1QuestAvailable; break;
        case 'EDM_EP1QuestAvailableFromNonActor': e_type = EDM_EP1QuestAvailableFromNonActor; break;
        case 'EDM_EP2QuestAvailable': e_type = EDM_EP2QuestAvailable; break;
        case 'EDM_EP2QuestAvailableFromNonActor': e_type = EDM_EP2QuestAvailableFromNonActor; break;
        case 'EDM_Torch': e_type = EDM_Torch; break;
        case 'EDM_HorseRaceTarget': e_type = EDM_HorseRaceTarget; break;
        case 'EDM_HorseRaceDummy': e_type = EDM_HorseRaceDummy; break;
        case 'EDM_EP3QuestAvailable': e_type = EDM_EP3QuestAvailable; break;
        case 'EDM_EP3QuestAvailableFromNonActor': e_type = EDM_EP3QuestAvailableFromNonActor; break;
        case 'EDM_Blacksmith': e_type = EDM_Blacksmith; break;
    }
    EnableDynamicMappin(tag, enable, e_type, showAlways);
}

quest function CjG_FocusClueManager(tag : name, actionType : name, isAvailable : bool, isInteractive : bool, isReusable : bool, isVisible : bool, wasDetected : bool, isIgnoringFM : bool) {
    var e_actionType : EFocusClueAttributeAction;
    switch (actionType) {
        case 'FCAA_ForceSet': e_actionType = FCAA_ForceSet; break;
        case 'FCAA_SetToTrue': e_actionType = FCAA_SetToTrue; break;
        case 'FCAA_SetToFalse': e_actionType = FCAA_SetToFalse; break;
        case 'FCAA_Switch': e_actionType = FCAA_Switch; break;
    }
    FocusClueManager(tag, e_actionType, isAvailable, isInteractive, isReusable, isVisible, wasDetected, isIgnoringFM);
}

quest function CjG_FocusEffect(actionType : name, effectName : name, effectEntityTag : name, duration : float) {
    var e_actionType : EFocusEffectActivationAction;
    switch (actionType) {
        case 'FEAA_Enable': e_actionType = FEAA_Enable; break;
        case 'FEAA_Disable': e_actionType = FEAA_Disable; break;
    }
    FocusEffect(e_actionType, effectName, effectEntityTag, duration);
}

quest function CjG_FocusSoundClueManager(tag : name, soundEffectType : name, startEventOverride : name, stopEventOverride : name) {
    var e_soundEffectType : EFocusModeSoundEffectType;
    switch (soundEffectType) {
        case 'FMSET_Gray': e_soundEffectType = FMSET_Gray; break;
        case 'FMSET_Red': e_soundEffectType = FMSET_Red; break;
        case 'FMSET_Green': e_soundEffectType = FMSET_Green; break;
        case 'FMSET_None': e_soundEffectType = FMSET_None; break;
    }
    FocusSoundClueManager(tag, e_soundEffectType, startEventOverride, stopEventOverride);
}

quest function CjG_ForceGwentFaction(val : name) {
    var e_val : EGwentCardFaction;
    switch (val) {
        case 'EGCF_Neutral': e_val = EGCF_Neutral; break;
        case 'EGCF_Kingdoms': e_val = EGCF_Kingdoms; break;
        case 'EGCF_Nilfgaard': e_val = EGCF_Nilfgaard; break;
        case 'EGCF_Monsters': e_val = EGCF_Monsters; break;
        case 'EGCF_Scoiatael': e_val = EGCF_Scoiatael; break;
        case 'EGCG_Skellige': e_val = EGCG_Skellige; break;
    }
    ForceGwentFaction(e_val);
}

quest function CjG_ForceInteractSwitch(tag : name, on : bool, switchType : name) {
    var e_switchType : PhysicalSwitchAnimationType;
    switch (switchType) {
        case 'PSAT_Undefined': e_switchType = PSAT_Undefined; break;
        case 'PSAT_Lever': e_switchType = PSAT_Lever; break;
        case 'PSAT_Button': e_switchType = PSAT_Button; break;
    }
    ForceInteractSwitch(tag, on, e_switchType);
}

quest function CjG_IsGwentFactionPlayable(faction : name) {
    var e_faction : EGwentCardFaction;
    switch (faction) {
        case 'EGCF_Neutral': e_faction = EGCF_Neutral; break;
        case 'EGCF_Kingdoms': e_faction = EGCF_Kingdoms; break;
        case 'EGCF_Nilfgaard': e_faction = EGCF_Nilfgaard; break;
        case 'EGCF_Monsters': e_faction = EGCF_Monsters; break;
        case 'EGCF_Scoiatael': e_faction = EGCF_Scoiatael; break;
        case 'EGCG_Skellige': e_faction = EGCG_Skellige; break;
    }
    IsGwentFactionPlayable(e_faction);
}

quest function CjG_ManageHudTimeOut(action : name, value : float) {
    var e_action : EHudTimeOutAction;
    switch (action) {
        case 'EHTOA_Start': e_action = EHTOA_Start; break;
        case 'EHTOA_Stop': e_action = EHTOA_Stop; break;
        case 'EHTOA_Add': e_action = EHTOA_Add; break;
    }
    ManageHudTimeOut(e_action, value);
}

quest function CjG_ManagerReplacerWarningArea(areaTag : name, enable : name) {
    var e_enable : EEnableMode;
    switch (enable) {
        case 'EEM_AsIs': e_enable = EEM_AsIs; break;
        case 'EEM_Enable': e_enable = EEM_Enable; break;
        case 'EEM_Disable': e_enable = EEM_Disable; break;
    }
    ManagerReplacerWarningArea(areaTag, e_enable);
}

quest function CjG_ModifyFactValueQuest(fact : string, action : name, value : float) {
    var e_action : EFactValueChangeMethod;
    switch (action) {
        case 'FVCM_Add': e_action = FVCM_Add; break;
        case 'FVCM_Substract': e_action = FVCM_Substract; break;
        case 'FVCM_Multiply': e_action = FVCM_Multiply; break;
        case 'FVCM_Divide': e_action = FVCM_Divide; break;
    }
    ModifyFactValueQuest(fact, e_action, value);
}

quest function CjG_PlayCameraEffect(animName : name, strength : float, bLoop : bool) {
    var e_animName : ECameraEffect;
    switch (animName) {
        case 'ECE_None': e_animName = ECE_None; break;
        case 'ECE_Drunk': e_animName = ECE_Drunk; break;
    }
    PlayCameraEffect(e_animName, strength, bLoop);
}

quest function CjG_PlayerModeQuest(playerMode : name, toggle : bool, snapToNavMeshSourceName : name, snapToNavMeshEnable : bool) {
    var e_playerMode : EPlayerMode;
    switch (playerMode) {
        case 'PM_Normal': e_playerMode = PM_Normal; break;
        case 'PM_Safe': e_playerMode = PM_Safe; break;
        case 'PM_Combat': e_playerMode = PM_Combat; break;
    }
    PlayerModeQuest(e_playerMode, toggle, snapToNavMeshSourceName, snapToNavMeshEnable);
}

quest function CjG_PlayerSelectQuickslotItem(itemName : name, itemCategory : name, useSign : bool, sign : name) {
    var e_sign : ESignType;
    switch (sign) {
        case 'ST_Aard': e_sign = ST_Aard; break;
        case 'ST_Yrden': e_sign = ST_Yrden; break;
        case 'ST_Igni': e_sign = ST_Igni; break;
        case 'ST_Quen': e_sign = ST_Quen; break;
        case 'ST_Axii': e_sign = ST_Axii; break;
        case 'ST_None': e_sign = ST_None; break;
    }
    PlayerSelectQuickslotItem(itemName, itemCategory, useSign, e_sign);
}

quest function CjG_RequestSwarmAttackPlayer(tag : name, stateAfterAttack : name, onArrivalFactID : string, onArrivalFactValue : int) {
    var e_stateAfterAttack : ESwarmStateOnArrival;
    switch (stateAfterAttack) {
        case 'SSOA_Idle': e_stateAfterAttack = SSOA_Idle; break;
        case 'SSOA_Shield': e_stateAfterAttack = SSOA_Shield; break;
        case 'SSOA_ClueBall': e_stateAfterAttack = SSOA_ClueBall; break;
    }
    RequestSwarmAttackPlayer(tag, e_stateAfterAttack, onArrivalFactID, onArrivalFactValue);
}

quest function CjG_RequestSwarmGoTo(lairTag : name, initialStateName : name, stateAfterAttack : name, onArrivalFactID : string, onArrivalFactValue : int) {
    var e_stateAfterAttack : ESwarmStateOnArrival;
    switch (stateAfterAttack) {
        case 'SSOA_Idle': e_stateAfterAttack = SSOA_Idle; break;
        case 'SSOA_Shield': e_stateAfterAttack = SSOA_Shield; break;
        case 'SSOA_ClueBall': e_stateAfterAttack = SSOA_ClueBall; break;
    }
    RequestSwarmGoTo(lairTag, initialStateName, e_stateAfterAttack, onArrivalFactID, onArrivalFactValue);
}

quest function CjG_SetGeraltLevel(level : int, path : name) {
    var e_path : EGeraltPath;
    switch (path) {
        case 'EGP_SWORD': e_path = EGP_SWORD; break;
        case 'EGP_SIGNS': e_path = EGP_SIGNS; break;
        case 'EGP_ALCHEMY': e_path = EGP_ALCHEMY; break;
    }
    SetGeraltLevel(level, e_path);
}

quest function CjG_SetImmortalQuest(targetsTag : name, immortalityMode : name, optional unconsciousMinDuration : float) {
    var e_immortalityMode : EActorImmortalityMode;
    switch (immortalityMode) {
        case 'AIM_None': e_immortalityMode = AIM_None; break;
        case 'AIM_Immortal': e_immortalityMode = AIM_Immortal; break;
        case 'AIM_Invulnerable': e_immortalityMode = AIM_Invulnerable; break;
        case 'AIM_Unconscious': e_immortalityMode = AIM_Unconscious; break;
    }
    SetImmortalQuest(targetsTag, e_immortalityMode, unconsciousMinDuration);
}

quest function CjG_SetMapPinStatus(type : name, tag : name, value : bool, dontChangeIfKnown : bool, dontChangeIfDiscovered : bool) {
    var e_type : EMapPinStatus;
    switch (type) {
        case 'EMPS_Undefined': e_type = EMPS_Undefined; break;
        case 'EMPS_Known': e_type = EMPS_Known; break;
        case 'EMPS_Discovered': e_type = EMPS_Discovered; break;
        case 'EMPS_Disabled': e_type = EMPS_Disabled; break;
    }
    SetMapPinStatus(e_type, tag, value, dontChangeIfKnown, dontChangeIfDiscovered);
}

quest function CjG_SetMapPinStatusEx(type : name, tag : name, value : bool, dontChangeIfKnown : bool, dontChangeIfDiscovered : bool) {
    var e_type : EMapPinStatus;
    switch (type) {
        case 'EMPS_Undefined': e_type = EMPS_Undefined; break;
        case 'EMPS_Known': e_type = EMPS_Known; break;
        case 'EMPS_Discovered': e_type = EMPS_Discovered; break;
        case 'EMPS_Disabled': e_type = EMPS_Disabled; break;
    }
    SetMapPinStatusEx(e_type, tag, value, dontChangeIfKnown, dontChangeIfDiscovered);
}

quest function CjG_SetPlayerBuildQuest(build : name, attributePoints : int) {
    var e_build : ESkillPresetBuild;
    switch (build) {
        case 'BUILD_FastAttack': e_build = BUILD_FastAttack; break;
        case 'BUILD_StrongAttack': e_build = BUILD_StrongAttack; break;
        case 'BUILD_FastStrongAttack': e_build = BUILD_FastStrongAttack; break;
        case 'BUILD_Defense': e_build = BUILD_Defense; break;
        case 'BUILD_Crossbow': e_build = BUILD_Crossbow; break;
        case 'BUILD_Yrden': e_build = BUILD_Yrden; break;
        case 'BUILD_Aard': e_build = BUILD_Aard; break;
        case 'BUILD_Axii': e_build = BUILD_Axii; break;
        case 'BUILD_AlternativeCast': e_build = BUILD_AlternativeCast; break;
        case 'BUILD_IgniQuen': e_build = BUILD_IgniQuen; break;
        case 'BUILD_Catalyst': e_build = BUILD_Catalyst; break;
        case 'BUILD_Potion': e_build = BUILD_Potion; break;
        case 'BUILD_Posion': e_build = BUILD_Posion; break;
        case 'BUILD_Bomb': e_build = BUILD_Bomb; break;
        case 'BUILD_Vitality': e_build = BUILD_Vitality; break;
        case 'BUILD_Schools': e_build = BUILD_Schools; break;
        case 'BUILD_Utility': e_build = BUILD_Utility; break;
        case 'BUILD_UtilityDefensive': e_build = BUILD_UtilityDefensive; break;
        case 'BUILD_Griffin': e_build = BUILD_Griffin; break;
        case 'BUILD_Viper': e_build = BUILD_Viper; break;
        case 'BUILD_Manticore': e_build = BUILD_Manticore; break;
    }
    SetPlayerBuildQuest(e_build, attributePoints);
}

quest function CjG_SoundEventQuest(eventName : string, saveBehavior : name) {
    var e_saveBehavior : ESoundEventSaveBehavior;
    switch (saveBehavior) {
        case 'SESB_Save': e_saveBehavior = SESB_Save; break;
        case 'SESB_DontSave': e_saveBehavior = SESB_DontSave; break;
        case 'SESB_ClearSaved': e_saveBehavior = SESB_ClearSaved; break;
    }
    SoundEventQuest(eventName, e_saveBehavior);
}

quest function CjG_SoundSetState(soundState : name) {
    var e_soundState : ESoundGameState;
    switch (soundState) {
        case 'ESGS_Default': e_soundState = ESGS_Default; break;
        case 'ESGS_Exploration': e_soundState = ESGS_Exploration; break;
        case 'ESGS_ExplorationNight': e_soundState = ESGS_ExplorationNight; break;
        case 'ESGS_Focus': e_soundState = ESGS_Focus; break;
        case 'ESGS_FocusNight': e_soundState = ESGS_FocusNight; break;
        case 'ESGS_FocusUnderwater': e_soundState = ESGS_FocusUnderwater; break;
        case 'ESGS_Combat': e_soundState = ESGS_Combat; break;
        case 'ESGS_CombatMonsterHunt': e_soundState = ESGS_CombatMonsterHunt; break;
        case 'ESGS_Dialog': e_soundState = ESGS_Dialog; break;
        case 'ESGS_DialogNight': e_soundState = ESGS_DialogNight; break;
        case 'ESGS_Cutscene': e_soundState = ESGS_Cutscene; break;
        case 'ESGS_Minigame': e_soundState = ESGS_Minigame; break;
        case 'ESGS_Death': e_soundState = ESGS_Death; break;
        case 'ESGS_Movie': e_soundState = ESGS_Movie; break;
        case 'ESGS_Boat': e_soundState = ESGS_Boat; break;
        case 'ESGS_MusicOnly': e_soundState = ESGS_MusicOnly; break;
        case 'ESGS_Underwater': e_soundState = ESGS_Underwater; break;
        case 'ESGS_UnderwaterCombat': e_soundState = ESGS_UnderwaterCombat; break;
        case 'ESGS_Paused': e_soundState = ESGS_Paused; break;
        case 'ESGS_Gwent': e_soundState = ESGS_Gwent; break;
        case 'ESGS_FocusUnderwaterCombat': e_soundState = ESGS_FocusUnderwaterCombat; break;
    }
    SoundSetState(e_soundState);
}

quest function CjG_TransferPlayerItemsQuest(designatedContainerTag : name, itemSelectionType : name, steelSword : bool, silverSword : bool, chestArmor : bool, boots : bool, gloves : bool, pants : bool, trophy : bool, mask : bool, bombs : bool, lures : bool, crossbow : bool, secondaryWeapon : bool, optional fromContainerToPlayer : bool, optional equipAfterTransfer : bool) {
    var e_itemSelectionType : EItemSelectionType;
    switch (itemSelectionType) {
        case 'IST_Equipped_Only': e_itemSelectionType = IST_Equipped_Only; break;
        case 'IST_All': e_itemSelectionType = IST_All; break;
    }
    TransferPlayerItemsQuest(designatedContainerTag, e_itemSelectionType, steelSword, silverSword, chestArmor, boots, gloves, pants, trophy, mask, bombs, lures, crossbow, secondaryWeapon, fromContainerToPlayer, equipAfterTransfer);
}

quest function CjG_UnlockGwentDeck(val : name) {
    var e_val : EGwentDeckUnlock;
    switch (val) {
        case 'EGDU_Northern_Kingdom': e_val = EGDU_Northern_Kingdom; break;
        case 'EGDU_Nilfgaard': e_val = EGDU_Nilfgaard; break;
        case 'EGDU_Scoiatael': e_val = EGDU_Scoiatael; break;
        case 'EGDU_No_Mans_Land': e_val = EGDU_No_Mans_Land; break;
    }
    UnlockGwentDeck(e_val);
}

quest function CjG_VibrateController(strength : name, duration : float) {
    var e_strength : EQuestPadVibrationStrength;
    switch (strength) {
        case 'EQPVS_VeryLight': e_strength = EQPVS_VeryLight; break;
        case 'EQPVS_Light': e_strength = EQPVS_Light; break;
        case 'EQPVS_Hard': e_strength = EQPVS_Hard; break;
        case 'EQPVS_VeryHard': e_strength = EQPVS_VeryHard; break;
    }
    VibrateController(e_strength, duration);
}

quest function CjG_VibrateMedallion(activate : bool, vibrateController : bool, optional vibrateStrength : name, optional vibrateDuration : float) {
    var e_vibrateStrength : EQuestPadVibrationStrength;
    switch (vibrateStrength) {
        case 'EQPVS_VeryLight': e_vibrateStrength = EQPVS_VeryLight; break;
        case 'EQPVS_Light': e_vibrateStrength = EQPVS_Light; break;
        case 'EQPVS_Hard': e_vibrateStrength = EQPVS_Hard; break;
        case 'EQPVS_VeryHard': e_vibrateStrength = EQPVS_VeryHard; break;
    }
    VibrateMedallion(activate, vibrateController, e_vibrateStrength, vibrateDuration);
}
